top=min(adi02.index)
base=max(adi02.index)
f, ax = plt.subplots(nrows=1, ncols=8, figsize=(15, 5), sharey=True)
f.subplots_adjust(top=0.6, wspace=0.2)
ax[0].plot(adi02.Cal, adi02.index, '-k')
ax[0].set_xlim(min(adi02['Cal']), max(adi02['Cal']))
ax[0].set_xlabel("Cal", color='k', size=16)
ax[0].set_ylabel('Depth', size=16)
ax[1].plot(adi02.GR, adi02.index, '-k')
ax[1].set_xlim(min(adi02['GR']), max(adi02['GR']))
ax[1].set_xlabel("GR", color='k', size=16)
ax[2].plot(adi02.Vp, adi02.index, '-k')
ax[2].set_xlim(min(adi02['Vp']), max(adi02['Vp']))
ax[2].set_xlabel("Vp in kms", color='k', size=16)
ax[3].plot(adi02.Vs, adi02.index, '-k')
ax[3].set_xlim(min(adi02['Vs']), max(adi02['Vs']))
ax[3].set_xlabel("Vs in kms", color='k', size=16)
ax[4].plot(adi02.Rho, adi02.index, '-k')
ax[4].set_xlim(min(adi02['Rho']), max(adi02['Rho']))
ax[4].set_xlabel("Rho in gcc", color='k', size=16)
ax[5].plot(adi02.Phit, adi02.index, '-k')
ax[5].set_xlim(min(adi02['Phit']), max(adi02['Phit']))
ax[5].set_xlabel("Phit", color='k', size=16)
ax[6].plot(adi02.Swt, adi02.index, '-k')
ax[6].set_xlim(min(adi02['Swt']), max(adi02['Swt']))
ax[6].set_xlabel("Swt", color='k', size=16)
ax[7].plot(adi02.Vsh, adi02.index, '-k')
ax[7].set_xlim(min(adi02['Vsh']), max(adi02['Vsh']))
ax[7].set_xlabel("Vsh", color='k', size=16)
for axes in ax:
    axes.set_ylim(top, base)
    axes.invert_yaxis()
    axes.yaxis.grid(True)
    axes.xaxis.grid(True)
    axes.xaxis.set_ticks_position('bottom')
    axes.xaxis.set_label_position('top')
    axes.grid(True,linestyle=':')
f.tight_layout()