lb=logs_blocked
zlb=lb.index
fig, ax = plt.subplots(nrows=1, ncols=4, figsize=(16,8), sharey=True)
fig.subplots_adjust(top=0.75,wspace=0.1)
for axes in ax:
        axes.set_ylim (top_plot,base_plot)
        axes.invert_yaxis()
        axes.yaxis.grid(True)
        axes.grid(True,linestyle=':', color='gray')
        axes.get_xaxis().set_visible(False) 
#Vsh track
ax01=ax[0].twiny()
ax01.set_xlim(0,1.0)
ax01.spines['top'].set_position(('outward',5))
ax01.set_xlabel("Vsh")
ax01.plot(lb.Vsh, zlb, label='Vsh', color='k')
ax01.set_xlabel('Vsh',color='k')    
ax01.tick_params(axis='x', colors='gray')
ax02=ax[0].twiny()
ax02.set_xlim(0,1.0)
ax02.plot(lb.Vsh_blk, zlb, label='Vsh blk', color='b', linewidth=4) 
ax02.spines['top'].set_position(('outward',40))
ax02.set_xlabel('Vsh Blk',color='b')    
ax02.tick_params(axis='x', colors='b')
#Vp track
ax11=ax[1].twiny()
ax11.set_xlim(2,4.5)
ax11.spines['top'].set_position(('outward',5))
ax11.set_xlabel("Vp")
ax11.plot(lb.Vp, zlb, label='Vp', color='k')
ax11.set_xlabel('Vp',color='k')    
ax11.tick_params(axis='x', colors='gray')
ax12=ax[1].twiny()
ax12.set_xlim(2,4.5)
ax12.plot(lb.Vp_blk, zlb, label='Vp blk', color='b', linewidth=4) 
ax12.spines['top'].set_position(('outward',40))
ax12.set_xlabel('Vp Blk',color='b')    
ax12.tick_params(axis='x', colors='b')
#Vs track
ax21=ax[2].twiny()
ax21.set_xlim(0.8,3.2)
ax21.spines['top'].set_position(('outward',5))
ax21.set_xlabel("Vs")
ax21.plot(lb.Vs, zlb, label='Vs', color='k')
ax21.set_xlabel('Vs',color='k')    
ax21.tick_params(axis='x', colors='gray')
ax22=ax[2].twiny()
ax22.set_xlim(0.8,3.2)
ax22.plot(lb.Vs_blk, zlb, label='Vs blk', color='b', linewidth=4) 
ax22.spines['top'].set_position(('outward',40))
ax22.set_xlabel('Vs Blk',color='b')    
ax22.tick_params(axis='x', colors='b')
#Rho track
ax31=ax[3].twiny()
ax31.set_xlim(1.5,2.8)
ax31.spines['top'].set_position(('outward',5))
ax31.set_xlabel("Rho")
ax31.plot(lb.Rho, zlb, label='Rho', color='k')
ax31.set_xlabel('Rho',color='k')    
ax31.tick_params(axis='x', colors='gray')
ax32=ax[3].twiny()
ax32.set_xlim(1.5,2.8)
ax32.plot(lb.Rho_blk, zlb, label='Rho blk', color='b', linewidth=4) 
ax32.spines['top'].set_position(('outward',40))
ax32.set_xlabel('Rho Blk',color='b')    
ax32.tick_params(axis='x', colors='b')
f.tight_layout() 